;; Adds a `C-c q' keybind to `erc-mode' to pick IRC color formatting codes
;; via a transient prefix
;;
;; TODO: Add color to the transient buffer choices e.g. via faces

(defun erc--fmt-insert-color-3 (fg &optional bg)
  (insert
   (if bg (format "\03%d,%d" fg bg) (format "\03%d" fg))))

(defmacro erc--fmt-color-define-prefix (description name fg)
  `(transient-define-prefix ,name ()
     [,(format "%s foreground, ? background" description)
      ("00" "white" (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 0)))
      ("01" "black" (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 1)))
      ("02" "blue" (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 2)))
      ("03" "green" (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 3)))
      ("04" "red" (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 4)))
      ("05" "brown" (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 5)))
      ("06" "magenta" (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 6)))
      ("07" "orange" (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 7)))
      ("08" "yellow" (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 8)))
      ("09" "lightgreen" (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 9)))
      ("10" "cyan" (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 10)))
      ("11" "lightcyan" (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 11)))
      ("12" "lightblue" (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 12)))
      ("13" "pink" (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 13)))
      ("14" "grey" (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 14)))
      ("15" "lightgrey" (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 15)))
      ("s" "spoilers" (lambda () (interactive) (erc--fmt-insert-color-3 ,fg ,fg)))
      ("RET" "none" (lambda () (interactive) (erc--fmt-insert-color-3 ,fg)))]))

(erc--fmt-color-define-prefix "White" erc--fmt-color-white 0)
(erc--fmt-color-define-prefix "Black" erc--fmt-color-black 1)
(erc--fmt-color-define-prefix "Blue" erc--fmt-color-blue 2)
(erc--fmt-color-define-prefix "Green" erc--fmt-color-green 3)
(erc--fmt-color-define-prefix "Red" erc--fmt-color-red 4)
(erc--fmt-color-define-prefix "Brown"  erc--fmt-color-brown 5)
(erc--fmt-color-define-prefix "Magenta" erc--fmt-color-magenta 6)
(erc--fmt-color-define-prefix "Orange" erc--fmt-color-orange 7)
(erc--fmt-color-define-prefix "Yellow" erc--fmt-color-yellow 8)
(erc--fmt-color-define-prefix "Light Green" erc--fmt-color-lightgreen 9)
(erc--fmt-color-define-prefix "Cyan" erc--fmt-color-cyan 10)
(erc--fmt-color-define-prefix "Light Byan" erc--fmt-color-lightcyan 11)
(erc--fmt-color-define-prefix "Light Blue" erc--fmt-color-lightblue 12)
(erc--fmt-color-define-prefix "Pink" erc--fmt-color-pink 13)
(erc--fmt-color-define-prefix "Grey" erc--fmt-color-grey 14)
(erc--fmt-color-define-prefix "Light Grey" erc--fmt-color-lightgrey 15)

(transient-define-prefix erc--fmt-color-1 ()
  ["Foreground"
   ("00" "white" erc--fmt-color-white)
   ("01" "black" erc--fmt-color-black)
   ("02" "blue" erc--fmt-color-blue)
   ("03" "green" erc--fmt-color-green)
   ("04" "red" erc--fmt-color-red)
   ("05" "brown" erc--fmt-color-brown)
   ("06" "magenta" erc--fmt-color-magenta)
   ("07" "orange" erc--fmt-color-orange)
   ("08" "yellow" erc--fmt-color-yellow)
   ("09" "lightgreen" erc--fmt-color-lightgreen)
   ("10" "cyan" erc--fmt-color-cyan)
   ("11" "lightcyan" erc--fmt-color-lightcyan)
   ("12" "lightblue" erc--fmt-color-lightblue)
   ("13" "pink" erc--fmt-color-pink)
   ("14" "grey" erc--fmt-color-grey)
   ("15" "lightgrey" erc--fmt-color-lightgrey)])

(define-key erc-mode-map (kbd "C-c q") 'erc--fmt-color-1)
