;; Adds a `C-c q' keybind to `erc-mode' to pick IRC color formatting codes
;; via a transient prefix

;; Color formatters
(defun erc--fmt-describe-color-white () (propertize "white" 'face '(:foreground "white")))
(defun erc--fmt-describe-color-black () (propertize "black" 'face '(:foreground "black")))
(defun erc--fmt-describe-color-blue () (propertize "blue" 'face '(:foreground "blue")))
(defun erc--fmt-describe-color-green () (propertize "green" 'face '(:foreground "green")))
(defun erc--fmt-describe-color-red () (propertize "red" 'face '(:foreground "red")))
(defun erc--fmt-describe-color-brown () (propertize "brown" 'face '(:foreground "brown")))
(defun erc--fmt-describe-color-magenta () (propertize "magenta" 'face '(:foreground "magenta")))
(defun erc--fmt-describe-color-orange () (propertize "orange" 'face '(:foreground "orange")))
(defun erc--fmt-describe-color-yellow () (propertize "yellow" 'face '(:foreground "yellow")))
(defun erc--fmt-describe-color-lightgreen () (propertize "light green" 'face '(:foreground "lightgreen")))
(defun erc--fmt-describe-color-cyan () (propertize "cyan" 'face '(:foreground "cyan")))
(defun erc--fmt-describe-color-lightcyan () (propertize "light cyan" 'face '(:foreground "lightcyan")))
(defun erc--fmt-describe-color-lightblue () (propertize "light blue" 'face '(:foreground "lightblue")))
(defun erc--fmt-describe-color-pink () (propertize "pink" 'face '(:foreground "pink")))
(defun erc--fmt-describe-color-grey () (propertize "grey" 'face '(:foreground "grey")))
(defun erc--fmt-describe-color-lightgrey () (propertize "light grey" 'face '(:foreground "light grey")))

;; Insertion function for control character
(defun erc--fmt-insert-color-3 (fg &optional bg)
  (insert
   (if bg (format "\03%d,%d" fg bg) (format "\03%d" fg))))

;; Macro helper for defining background color transient
(defmacro erc--fmt-color-define-prefix (description name fg)
  `(transient-define-prefix ,name ()
     [,(format "%s foreground, ? background" description)
      ("00" erc--fmt-describe-color-white (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 0)))
      ("01" erc--fmt-describe-color-black (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 1)))
      ("02" erc--fmt-describe-color-blue (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 2)))
      ("03" erc--fmt-describe-color-green (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 3)))
      ("04" erc--fmt-describe-color-red (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 4)))
      ("05" erc--fmt-describe-color-brown (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 5)))
      ("06" erc--fmt-describe-color-magenta (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 6)))
      ("07" erc--fmt-describe-color-orange (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 7)))
      ("08" erc--fmt-describe-color-yellow (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 8)))
      ("09" erc--fmt-describe-color-lightgreen (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 9)))
      ("10" erc--fmt-describe-color-cyan (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 10)))
      ("11" erc--fmt-describe-color-lightcyan (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 11)))
      ("12" erc--fmt-describe-color-lightblue (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 12)))
      ("13" erc--fmt-describe-color-pink (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 13)))
      ("14" erc--fmt-describe-color-grey (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 14)))
      ("15" erc--fmt-describe-color-lightgrey (lambda () (interactive) (erc--fmt-insert-color-3 ,fg 15)))
      ("s" "spoilers" (lambda () (interactive) (erc--fmt-insert-color-3 ,fg ,fg)))
      ("RET" "none" (lambda () (interactive) (erc--fmt-insert-color-3 ,fg)))]))

;; Define background color prefixes
(erc--fmt-color-define-prefix "White" erc--fmt-color-white 0)
(erc--fmt-color-define-prefix "Black" erc--fmt-color-black 1)
(erc--fmt-color-define-prefix "Blue" erc--fmt-color-blue 2)
(erc--fmt-color-define-prefix "Green" erc--fmt-color-green 3)
(erc--fmt-color-define-prefix "Red" erc--fmt-color-red 4)
(erc--fmt-color-define-prefix "Brown"  erc--fmt-color-brown 5)
(erc--fmt-color-define-prefix "Magenta" erc--fmt-color-magenta 6)
(erc--fmt-color-define-prefix "Orange" erc--fmt-color-orange 7)
(erc--fmt-color-define-prefix "Yellow" erc--fmt-color-yellow 8)
(erc--fmt-color-define-prefix "Light Green" erc--fmt-color-lightgreen 9)
(erc--fmt-color-define-prefix "Cyan" erc--fmt-color-cyan 10)
(erc--fmt-color-define-prefix "Light Byan" erc--fmt-color-lightcyan 11)
(erc--fmt-color-define-prefix "Light Blue" erc--fmt-color-lightblue 12)
(erc--fmt-color-define-prefix "Pink" erc--fmt-color-pink 13)
(erc--fmt-color-define-prefix "Grey" erc--fmt-color-grey 14)
(erc--fmt-color-define-prefix "Light Grey" erc--fmt-color-lightgrey 15)

;; Define foreground prefix
(transient-define-prefix erc--fmt-color-1 ()
  ["Foreground"
   ("00" erc--fmt-describe-color-white erc--fmt-color-white)
   ("01" erc--fmt-describe-color-black erc--fmt-color-black)
   ("02" erc--fmt-describe-color-blue erc--fmt-color-blue)
   ("03" erc--fmt-describe-color-green erc--fmt-color-green)
   ("04" erc--fmt-describe-color-red erc--fmt-color-red)
   ("05" erc--fmt-describe-color-brown erc--fmt-color-brown)
   ("06" erc--fmt-describe-color-magenta erc--fmt-color-magenta)
   ("07" erc--fmt-describe-color-orange erc--fmt-color-orange)
   ("08" erc--fmt-describe-color-yellow erc--fmt-color-yellow)
   ("09" erc--fmt-describe-color-lightgreen erc--fmt-color-lightgreen)
   ("10" erc--fmt-describe-color-cyan erc--fmt-color-cyan)
   ("11" erc--fmt-describe-color-lightcyan erc--fmt-color-lightcyan)
   ("12" erc--fmt-describe-color-lightblue erc--fmt-color-lightblue)
   ("13" erc--fmt-describe-color-pink erc--fmt-color-pink)
   ("14" erc--fmt-describe-color-grey erc--fmt-color-grey)
   ("15" erc--fmt-describe-color-lightgrey erc--fmt-color-lightgrey)])

;; Install binding
(define-key erc-mode-map (kbd "C-c q") 'erc--fmt-color-1)
